name: clean-up-runners
on: workflow_dispatch
jobs:
    manage-runners:
        runs-on: ubuntu-latest
        steps:
          - uses: cellinacywinska/clean-up-offline-github-runners@develop
            with:
              repo-name: 'dummy-repo-ephemeral-runners'
              repo-owner: 'LorenzoDrudi'
              personal-access-token: '${{ secrets.ACCESS_TOKEN }}'